---
abstract: 'The great new Catalyst::Controller::POD!'
author:
  - 'Moritz Onken, C<< <onken at houseofdesign.de> >>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-POD
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Catalyst::Controller: 0
  Class::Accessor::Fast: 0
  File::Find: 0
  File::ShareDir: 0
  File::Slurp: 0
  JSON::XS: 0
  LWP::Simple: 0
  List::MoreUtils: 0
  Pod::POM: 0
  Pod::Simple: 0
  Test::More: 0
version: 0.01_02
